### ISSUE TITLE
Great Work

### ISSUE THREAD

**Issue by L7NEG** [YimMenu-Lua/Removed-vehicles#1]
I think you are the one who are in the discord server fr can I use the option included with your credits since you got all Globals of the 200 vehicles which ik damn W work from you

**Comment by L7NEG** [comment]
Or if you just wanted to do it yourself you can open a pr in either this repo https://github.com/UltimateMenu/UltimateMenu or the one in Yimura Lua Repo

**Comment by visionary2709** [comment]
> I think you are the one who are in the discord server fr can I use the option included with your credits since you got all Globals of the 200 vehicles which ik damn W work from you

Thank you, of course please include it in your script, better to reach all those who want to use it.

**Comment by L7NEG** [comment]
> > I think you are the one who are in the discord server fr can I use the option included with your credits since you got all Globals of the 200 vehicles which ik damn W work from you
> 
> Thank you, of course please include it in your script, better to reach all those who want to use it.

You are welcome bro I appreciate it + Credits must be given as you are the only one who done it for 1.69 ❤🗣 keep it up man + you can close this if you want to
